### ISSUE TITLE
Codeception seems breaks the session in Phpstorm

### ISSUE THREAD

**Issue by yujin1st** [Codeception/module-yii2#44]
### What steps will reproduce the problem?
1. Write simple functional test that logs user in and moves by pages with Yii framework

```
    $I->amOnRoute('/');
    $I->assertTrue(Yii::$app->user->isGuest);
    $I->amLoggedInAs(User::findUserByUsername('admin'));
    $I->assertFalse(Yii::$app->user->isGuest);
    $I->amOnRoute('/');
    $I->assertFalse(Yii::$app->user->isGuest);
```
2. Run test

### What is the expected result?
 All should be fine
### What do you get instead?
Test runs in console and fails in Phpstorm (first test in screenshot )
If you comment first line that opens the page before all tests complete without error (second test in screenshot)

![2017-08-30 12 12 12](https://user-images.githubusercontent.com/2317913/29853725-7ccb89a4-8d7c-11e7-8b1a-bd5409ad16bc.png)

### Additional info
At first i thought it ide issue, but after i discovered it appeared only if "amOnRoute" is on first string, i become concerned about yii. 
After submitting [issue to yii](https://github.com/yiisoft/yii2/issues/14737) i've been sent here =)
As i found Yii module just call internal \Codeception\Lib\InnerBrowser::amOnPage method

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1
| PhpStorm | Last EAP and stable versions
| Operating system | Mac 10.12.5

**Comment by marcovtwout** [comment]
@SamMousa Is this issue actually fixed with a code change or just marked completed?

**Comment by SamMousa** [comment]
No It's not fixed, nor marked as completed. It's marked as closed. Since it stems from 2017 and there has been no activity on it for quite a while.

**Comment by asamats** [comment]
But the problem did not disappear.

**Comment by SamMousa** [comment]
Apologies, apparently I marked it in correctly. It has now been marked as not planned, hopefully that clears up any confusion.

> But the problem did not disappear.

That's not relevant, if no one is working on the issue and the information and screenshot stem from 2017 they are no longer useful. If you want to open a new issue and work on fixing it then by all means go ahead.
Just be aware that given the lack of contributors, just reporting an issue only a few people are facing is not going to do anything.

**Comment by sanchezzzhak** [comment]
```php
    protected function _before()
    {
        $session = Stub::construct(Session::class, [], [
            'open' => function() {},
            'init' => function() {},
            'close' => function() {},
        ]);
        \Yii::$app->setComponents([
            'session' => $session
        ]);
    }
```
